language: python
python:
  - "2.7"
# command to install dependencies
env:
install:
  - "pip install flake8 --use-mirrors"
  - "pip install httpretty --use-mirrors"
  - "python setup.py develop"
before_script: "flake8 nsnitro --ignore=E501,F401,F403,W291,W293"
# command to run tests
script: "python setup.py nosetests"
